# 存放数据库配置

DB_USERNAME = 'root'
DB_PASSWORD = ''
# DB_HOST = '127.0.0.1'
DB_HOST = "47.74.148.75"
DB_PORT = '3306'
DB_NAME = 'qa'

DB_URI = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (DB_USERNAME, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME)

SQLALCHEMY_DATABASE_URI = DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = False
