"""empty message

Revision ID: 6579a33e749d
Revises: 
Create Date: 2018-08-15 23:13:39.047642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6579a33e749d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('q_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('finalurl', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('q_keyword',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['q_a.id'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('q_keyword')
    op.drop_table('q_a')
    # ### end Alembic commands ###
