"""empty message

Revision ID: 909d8aaaf3d3
Revises: 6579a33e749d
Create Date: 2018-08-16 14:17:21.013074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909d8aaaf3d3'
down_revision = '6579a33e749d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('q_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('finalurl', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('q_keyword',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['aid'], ['q_a.id'], ),
    sa.PrimaryKeyConstraint('aid', 'keyword')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('q_keyword')
    op.drop_table('q_a')
    # ### end Alembic commands ###
